import type { LevelData } from "../types/budget";

// Export constants that can't be in .d.ts files
export const months = [
  "apr qty",
  "apr rate",
  "apr amount",
  "april",
  "may qty",
  "may rate",
  "may amount",
  "may",
  "jun qty",
  "jun rate",
  "jun amount",
  "june",
  "jul qty",
  "jul rate",
  "jul amount",
  "july",
  "aug qty",
  "aug rate",
  "aug amount",
  "august",
  "sep qty",
  "sep rate",
  "sep amount",
  "september",
  "oct qty",
  "oct rate",
  "oct amount",
  "october",
  "nov qty",
  "nov rate",
  "nov amount",
  "november",
  "dec qty",
  "dec rate",
  "dec amount",
  "december",
  "jan qty",
  "jan rate",
  "jan amount",
  "january",
  "feb qty",
  "feb rate",
  "feb amount",
  "february",
  "mar qty",
  "mar rate",
  "mar amount",
  "march",
];

export const headerMonth = [
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
  "January",
  "February",
  "March",
];

// map each month to its quarter key
// ✅ Correct way: constrain the allowed values
export const monthToQKey: Record<
  string,
  "totalQ1" | "totalQ2" | "totalQ3" | "totalQ4"
> = {
  Apr: "totalQ1",
  May: "totalQ1",
  Jun: "totalQ1",
  Jul: "totalQ2",
  Aug: "totalQ2",
  Sep: "totalQ2",
  Oct: "totalQ3",
  Nov: "totalQ3",
  Dec: "totalQ3",
  Jan: "totalQ4",
  Feb: "totalQ4",
  Mar: "totalQ4",
};

export const monthFields = [
  { short: "Apr", name: "April", full: "april" },
  { short: "May", name: "May", full: "may" },
  { short: "Jun", name: "June", full: "june" },
  { short: "Jul", name: "July", full: "july" },
  { short: "Aug", name: "August", full: "august" },
  { short: "Sep", name: "September", full: "september" },
  { short: "Oct", name: "October", full: "october" },
  { short: "Nov", name: "November", full: "november" },
  { short: "Dec", name: "December", full: "december" },
  { short: "Jan", name: "January", full: "january" },
  { short: "Feb", name: "February", full: "february" },
  { short: "Mar", name: "March", full: "march" },
];

export const mainMonths = [
  "Apr",
  "May",
  "Jun",
  "Jul",
  "Aug",
  "Sep",
  "Oct",
  "Nov",
  "Dec",
  "Jan",
  "Feb",
  "Mar",
];

export const getBaseStructure = (): LevelData => ({
  // Count: 0,
  "apr qty": 0,
  "apr rate": 0,
  "apr amount": 0,
  april: 0,
  "may qty": 0,
  "may rate": 0, 
  "may amount": 0,  
  may: 0,
  "jun qty": 0,
  "jun rate": 0,
  "jun amount": 0,
  june: 0,
  "jul qty": 0,
  "jul rate": 0,
  "jul amount": 0,
  july: 0,
  "aug qty": 0,
  "aug rate": 0,
  "aug amount": 0,
  august: 0,
  "sep qty": 0,
  "sep rate": 0,
  "sep amount": 0,
  september: 0,
  "oct qty": 0,
  "oct rate": 0,
  "oct amount": 0,
  october: 0,
  "nov qty": 0,
  "nov rate": 0,
  "nov amount": 0,
  november: 0,
  "dec qty": 0,
  "dec rate": 0,
  "dec amount": 0,
  december: 0,
  "jan qty": 0,
  "jan rate": 0,
  "jan amount": 0,
  january: 0,
  "feb qty": 0,
  "feb rate": 0,
  "feb amount": 0,
  february: 0,
  "mar qty": 0,
  "mar rate": 0,
  "mar amount": 0,
  march : 0,
  budgetDetailsId: 0,
});

export const monthToQuarter: Record<string, keyof import("../types/travel").totalschema> = {
  apr: "totalQ1",
  may: "totalQ1",
  jun: "totalQ1",
  jul: "totalQ2",
  aug: "totalQ2",
  sep: "totalQ2",
  oct: "totalQ3",
  nov: "totalQ3",
  dec: "totalQ3",
  jan: "totalQ4",
  feb: "totalQ4",
  mar: "totalQ4",
};


export const monthMap: Record<string, string> = {
  jan: "january",
  feb: "february",
  mar: "march",
  apr: "april",
  may: "may",
  jun: "june",
  jul: "july",
  aug: "august",
  sep: "september",
  oct: "october",
  nov: "november",
  dec: "december",
};
