export const months = [
    "Qty1",
    "Apr",
    "May",
    "Jun",
    "Q1",
    "Qty2",
    "Jul",
    "Aug",
    "Sep",
    "Q2",
    "Qty3",
    "Oct",
    "Nov",
    "Dec",
    "Q3",
    "Qty4",
    "Jan",
    "Feb",
    "Mar",
    "Q4",
    "Total",
  ];

  export const bandLevelMapping: Record<string, string> = {
    I: "Assistant",
    II: "Associate",
    III: "Manager",
    IV: "Senior Manager",
    V: "AVP",
    VI: "VP",
    VII: "CXO/Director",
    "Others - Interns, Volunteers, PTCs": "N/A",
    "Staff Benefits": "N/A",
  };