  import type { LevelData } from "../types/budget";

// Export constants that can't be in .d.ts files
export const months = [
  "apr qty",
  "apr rate",
  "apr amount",
  // "april",
  "apr notes",
  "may qty",
  "may rate",
  "may amount",
  // "may",
  "may notes",
  "jun qty",
  "jun rate",
  "jun amount",
  // "june",
  "jun notes",
  "Q1 qty",
  "Q1 rate",
  "Q1 amount",
  "jul qty",
  "jul rate",
  "jul amount",
  // "july",
  "jul notes",
  "aug qty",
  "aug rate",
  "aug amount",
  // "august",
  "aug notes",
  "sep qty",
  "sep rate",
  "sep amount",
  // "september",
  "sep notes",
  "Q2 qty",
  "Q2 rate",
  "Q2 amount",
  "oct qty",
  "oct rate",
  "oct amount",
  // "october",
  "oct notes",
  "nov qty",
  "nov rate",
  "nov amount",
  // "november",
  "nov notes",
  "dec qty",
  "dec rate",
  "dec amount",
  // "december",
  "dec notes",
  "Q3 qty",
  "Q3 rate",
  "Q3 amount",
  "jan qty",
  "jan rate",
  "jan amount",
  // "january",
  "jan notes",
  "feb qty",
  "feb rate",
  "feb amount",
  // "february",
  "feb notes",
    "mar qty",
  "mar rate",
  "mar amount",
  // "march",
  "mar notes",
  "Q4 qty",
  "Q4 rate",
  "Q4 amount",
];

export const headerMonth = [
  "April",
  "May",
  "June",
  "Q1",
  "July",
  "August",
  "September",
  "Q2",
  "October",
  "November",
  "December",
  "Q3",
  "January",
  "February",
  "March",
  "Q4",
];

// map each month to its quarter key
// ✅ Correct way: constrain the allowed values
export const monthToQKey: Record<
  string,
  "totalQ1" | "totalQ2" | "totalQ3" | "totalQ4"
> = {
  Apr: "totalQ1",
  May: "totalQ1",
  Jun: "totalQ1",
  Jul: "totalQ2",
  Aug: "totalQ2",
  Sep: "totalQ2",
  Oct: "totalQ3",
  Nov: "totalQ3",
  Dec: "totalQ3",
  Jan: "totalQ4",
  Feb: "totalQ4",
  Mar: "totalQ4",
};

export const monthFields = [
  { short: "Apr", name: "April", full: "april" },
  { short: "May", name: "May", full: "may" },
  { short: "Jun", name: "June", full: "june" },
  { short: "Jul", name: "July", full: "july" },
  { short: "Aug", name: "August", full: "august" },
  { short: "Sep", name: "September", full: "september" },
  { short: "Oct", name: "October", full: "october" },
  { short: "Nov", name: "November", full: "november" },
  { short: "Dec", name: "December", full: "december" },
  { short: "Jan", name: "January", full: "january" },
  { short: "Feb", name: "February", full: "february" },
  { short: "Mar", name: "March", full: "march" },
];

export const mainMonths = [
  "Apr",
  "May",
  "Jun",
  "Jul",
  "Aug",
  "Sep",
  "Oct",
  "Nov",
  "Dec",
  "Jan",
  "Feb",
  "Mar",
];

export const getBaseStructure = (): LevelData => ({
  // Count: 0,
  "apr qty": 0,
  "apr rate": 0,
  "apr amount": 0,
  april: 0,
  "apr notes": "",
  "may qty": 0,
  "may rate": 0, 
  "may amount": 0,  
  may: 0,
  "may notes": "",
  "jun qty": 0,
  "jun rate": 0,
  "jun amount": 0,
  june: 0,
  "jun notes": "",
  // Q1 totals
  "Q1 qty": 0,
  "Q1 rate": 0,
  "Q1 amount": 0,
  "jul qty": 0,
  "jul rate": 0,
  "jul amount": 0,
  july: 0,
  "jul notes": "",
  "aug qty": 0,
  "aug rate": 0,
  "aug amount": 0,
  august: 0,
  "aug notes": "",
  "sep qty": 0,
  "sep rate": 0,
  "sep amount": 0,
  september: 0,
  "sep notes": "",
  // Q2 totals
  "Q2 qty": 0,
  "Q2 rate": 0,
  "Q2 amount": 0,
  "oct qty": 0,
  "oct rate": 0,
  "oct amount": 0,
  october: 0,
  "oct notes": "",
  "nov qty": 0,
  "nov rate": 0,
  "nov amount": 0,
  november: 0,
  "nov notes": "",
  "dec qty": 0,
  "dec rate": 0,
  "dec amount": 0,
  december: 0,
  "dec notes": "",
  // Q3 totals
  "Q3 qty": 0,
  "Q3 rate": 0,
  "Q3 amount": 0,
  "jan qty": 0,
  "jan rate": 0,
  "jan amount": 0,
  january: 0,
  "jan notes": "",
  "feb qty": 0,
  "feb rate": 0,
  "feb amount": 0,
  february: 0,
  "feb notes": "",
  "mar qty": 0,
  "mar rate": 0,
  "mar amount": 0,
  march : 0,
  "mar notes": "",
  // Q4 totals
  "Q4 qty": 0,
  "Q4 rate": 0,
  "Q4 amount": 0,
  budgetDetailsId: 0,
});

export const monthToQuarter: Record<string, keyof import("../types/travel").totalschema> = {
  apr: "totalQ1",
  may: "totalQ1",
  jun: "totalQ1",
  jul: "totalQ2",
  aug: "totalQ2",
  sep: "totalQ2",
  oct: "totalQ3",
  nov: "totalQ3",
  dec: "totalQ3",
  jan: "totalQ4",
  feb: "totalQ4",
  mar: "totalQ4",
};


export const monthMap: Record<string, string> = {
  jan: "january",
  feb: "february",
  mar: "march",
  apr: "april",
  may: "may",
  jun: "june",
  jul: "july",
  aug: "august",
  sep: "september",
  oct: "october",
  nov: "november",
  dec: "december",
};

export const displayColumnMap: Record<string, string> = {
  "apr qty": "Qty",
  "apr rate": "Rate",
  "apr amount": "Amount",
  "april": "April",
  "apr notes": "Notes",
  "may qty": "Qty",
  "may rate": "Rate",
  "may amount": "Amount",
  "may": "May",
  "may notes": "Notes",
  "jun qty": "Qty",
  "jun rate": "Rate",
  "jun amount": "Amount", 
  "june": "June",
  "jun notes": "Notes",
  "jul qty": "Qty",
  "jul rate": "Rate",
  "jul amount": "Amount",
  "july": "July",
  "jul notes": "Notes",
  "aug qty": "Qty",
  "aug rate": "Rate",
  "aug amount": "Amount",
  "august": "August",
  "aug notes": "Notes",
  "sep qty": "Qty",
  "sep rate": "Rate",
  "sep amount": "Amount",
  "september": "September",
  "sep notes": "Notes",
  "oct qty": "Qty",
  "oct rate": "Rate",
  "oct amount": "Amount",
  "october": "October",
  "oct notes": "Notes",
  "nov qty": "Qty",
  "nov rate": "Rate",
  "nov amount": "Amount",
  "november": "November",
  "nov notes": "Notes",
  "dec qty": "Qty",
  "dec rate": "Rate",
  "dec amount": "Amount",
  "december": "December",  
  "dec notes": "Notes",
  "jan qty": "Qty",
  "jan rate": "Rate",
  "jan amount": "Amount",
  "january": "January",
  "jan notes": "Notes",
  "feb qty": "Qty",
  "feb rate": "Rate",
  "feb amount": "Amount",
  // "february": "February",
  "feb notes": "Notes",
  "mar qty": "Qty",
  "mar rate": "Rate",
  "mar amount": "Amount",
  "march": "March",
  "mar notes": "Notes",
}
