import { subTravelSchema } from "../types/travel";

export const subTravels: subTravelSchema[] = [
  { map: 0, id: 0, name: "All" },
  { map: 1, id: 7, name: "Assistant I" },
  { map: 2, id: 8, name: "Associate II" },
  { map: 3, id: 9, name: "Manager III" },
  { map: 4, id: 10, name: "Senior Manager IV" },
  { map: 5, id: 11, name: "AVP V" },
  { map: 6, id: 12, name: "VP VI" },
  { map: 7, id: 13, name: "CXO/Director VII" },
  // { map: 8, id: 14, name: "Others - Interns, Volunteers, PTCs VIII" },
];

export const months = [
  "apr qty",
  "apr trips",
  "apr rate",
  "apr amount",
  // "april",
  "may qty",
  "may trips",
  "may rate",
  "may amount",
  // "may",
  "jun qty",
  "jun trips",
  "jun rate",
  "jun amount",
  "Q1 qty",
  "Q1 rate",
  "Q1 amount",
  // "june",
  "jul qty",
  "jul trips",
  "jul rate",
  "jul amount",
  // "july",
  "aug qty",
  "aug trips",
  "aug rate",
  "aug amount",
  // "august",
  "sep qty",
  "sep trips",
  "sep rate",
  "sep amount",
  // "september",
  "Q2 qty",
  "Q2 rate",
  "Q2 amount",
  "oct qty",
  "oct trips",
  "oct rate",
  "oct amount",
  // "october",
  "nov qty",
  "nov trips",
  "nov rate",
  "nov amount",
  // "november",
  "dec qty",
  "dec trips",
  "dec rate",
  "dec amount",
  // "december",
  "Q3 qty",
  "Q3 rate",
  "Q3 amount",
  "jan qty",
  "jan trips",
  "jan rate",
  "jan amount",
  // "january",
  "feb qty",
  "feb trips",    
  "feb rate",
  "feb amount",
  // "february",
  "mar qty",
  "mar trips",
  "mar rate",
  "mar amount",
  // "march",
  "Q4 qty",
  "Q4 rate",
  "Q4 amount",
];

export const getBaseStructure = () => ({
  Count: 0,
  "apr qty": 0,
  "apr trips": 0,
  "apr rate": 0,
  "apr amount": 0,
  april: 0,
  "may qty": 0,
  "may trips": 0,
  "may rate": 0, 
  "may amount": 0,  
  may: 0,
  "jun qty": 0,
  "jun trips": 0,
  "jun rate": 0,
  "jun amount": 0,
  june: 0,
  // Q1 totals
  "Q1 qty": 0,
  "Q1 rate": 0,
  "Q1 amount": 0,
  "jul qty": 0,
  "jul trips": 0,
  "jul rate": 0,
  "jul amount": 0,
  july: 0,
  "aug qty": 0,
  "aug trips": 0,
  "aug rate": 0,
  "aug amount": 0,
  august: 0,
  "sep qty": 0,
  "sep trips": 0,
      "sep rate": 0,
  "sep amount": 0,
  september: 0,
  // Q2 totals
  "Q2 qty": 0,
  "Q2 rate": 0,
  "Q2 amount": 0,
  "oct qty": 0,
  "oct trips": 0,
  "oct rate": 0,
  "oct amount": 0,
  october: 0,
  "nov qty": 0,
  "nov trips": 0,
  "nov rate": 0,
  "nov amount": 0,
  november: 0,
  "dec qty": 0,
  "dec trips": 0,
  "dec rate": 0,
  "dec amount": 0,
  december: 0,
  // Q3 totals
  "Q3 qty": 0,
  "Q3 rate": 0,
  "Q3 amount": 0,
  "jan qty": 0,
  "jan trips": 0,
      "jan rate": 0,
  "jan amount": 0,
  january: 0,
  "feb qty": 0,
  "feb trips": 0,
  "feb rate": 0,
  "feb amount": 0,
  february: 0,
  "mar qty": 0,
  "mar trips": 0,
  "mar rate": 0,
  "mar amount": 0,
  march : 0,
  // Q4 totals
  "Q4 qty": 0,
  "Q4 rate": 0,
  "Q4 amount": 0,
  budgetDetailsId: 0,
});

export const headerMonth = [
  "April",
  "May",
  "June",
  "Q1",
  "July",
  "August",
  "September",
  "Q2",
  "October",
  "November",
  "December",
  "Q3",
  "January",
  "February",
  "March",
  "Q4",
];

export const monthToQuarter: Record<string, keyof import("../types/travel").totalschema> = {
  apr: "totalQ1",
  may: "totalQ1",
  jun: "totalQ1",
  jul: "totalQ2",
  aug: "totalQ2",
  sep: "totalQ2",
  oct: "totalQ3",
  nov: "totalQ3",
  dec: "totalQ3",
  jan: "totalQ4",
  feb: "totalQ4",
  mar: "totalQ4",
};

export const displayNameMap: Record<string, string> = {
  "Local conveyance (External)":    "Local",
  "Outstation travel (External)":   "Outstation",
  "Accomodation (External)":         "Hotel",
  "Per diem for employees (External)":        "Per deim",
};

export const displayColumnMap: Record<string, string> = {
  "apr qty": " No",
  "apr trips": " Trips",
  "apr rate": " Rate",
  "apr amount": " Total",
  "april": "april",
  "may qty": " No",
  "may trips": " Trips",
  "may rate": " Rate",
  "may amount": " Total",
  "may": "may",
  "jun qty": " No",
  "jun trips": " Trips",
  "jun rate": " Rate",
  "jun amount": " Total",
  "june": "june",
  // Q1
  "Q1 qty": " No",
  "Q1 rate": " Rate",
  "Q1 amount": " Total",
  "jul qty": " No",
  "jul trips": " Trips",
  "jul rate": " Rate",
  "jul amount": " Total",
  "july": "july",
  "aug qty": " No",
  "aug trips": " Trips",
  "aug rate": " Rate",
  "aug amount": " Total",
  "august": "august",
  "sep qty": " No",
  "sep trips": " Trips",
  "sep rate": " Rate",
  "sep amount": " Total",
  "september": "september",
  // Q2
  "Q2 qty": " No",
  "Q2 rate": " Rate",
  "Q2 amount": " Total",
  "oct qty": " No",
  "oct trips": " Trips",
  "oct rate": " Rate",
  "oct amount": " Total",
  "october": "october",
  "nov qty": "No",
  "nov trips": "Trips",
  "nov rate": "Rate",
  "nov amount": "Total",
  "november": "november",
  "dec qty": " No",
  "dec trips": "Trips",
  "dec rate": " Rate",
  "dec amount": "Total",
  "december": "december",
  // Q3
  "Q3 qty": " No",
  "Q3 rate": " Rate",
  "Q3 amount": " Total",
    "jan qty": " No",
  "jan trips": " Trips",
  "jan rate": " Rate",
  "jan amount": " Total",
  "january": "january",
  "feb qty": " No",
  "feb trips": " Trips",
    "feb rate": " Rate",
  "feb amount": " Total",
  "february": "february",
  "mar qty": " No",
  "mar trips": " Trips",
  "mar rate": " Rate",
  "mar amount": " Total",
  "march": "march",
  // Q4
  "Q4 qty": " No",
  "Q4 rate": " Rate",
  "Q4 amount": " Total",
};

export const monthMap: Record<string, string> = {
  jan: "january",
  feb: "february",
  mar: "march",
  apr: "april",
  may: "may",
  jun: "june",
  jul: "july",
  aug: "august",
  sep: "september",
  oct: "october",
  nov: "november",
  dec: "december",
};
