import { subTravelSchema } from "../types/travel";

export const subTravels: subTravelSchema[] = [
  { map: 0, id: 0, name: "All" },
  { map: 1, id: 7, name: "Assistant I" },
  { map: 2, id: 8, name: "Associate II" },
  { map: 3, id: 9, name: "Manager III" },
  { map: 4, id: 10, name: "Senior Manager IV" },
  { map: 5, id: 11, name: "AVP V" },
  { map: 6, id: 12, name: "VP VI" },
  { map: 7, id: 13, name: "CXO/Director VII" },
  // { map: 8, id: 14, name: "Others - Interns, Volunteers, PTCs VIII" },
];

export const months = [
  "apr qty",
  "apr rate",
  "apr amount",
  "april",
  "may qty",
  "may rate",
  "may amount",
  "may",
  "jun qty",
  "jun rate",
  "jun amount",
  "june",
  "jul qty",
  "jul rate",
  "jul amount",
  "july",
  "aug qty",
  "aug rate",
  "aug amount",
  "august",
  "sep qty",
  "sep rate",
  "sep amount",
  "september",
  "oct qty",
  "oct rate",
  "oct amount",
  "october",
  "nov qty",
  "nov rate",
  "nov amount",
  "november",
  "dec qty",
  "dec rate",
  "dec amount",
  "december",
  "jan qty",
  "jan rate",
  "jan amount",
  "january",
  "feb qty",
  "feb rate",
  "feb amount",
  "february",
  "mar qty",
  "mar rate",
  "mar amount",
  "march",
];

export const getBaseStructure = () => ({
  Count: 0,
  "apr qty": 0,
  "apr rate": 0,
  "apr amount": 0,
  april: 0,
  "may qty": 0,
  "may rate": 0, 
  "may amount": 0,  
  may: 0,
  "jun qty": 0,
  "jun rate": 0,
  "jun amount": 0,
  june: 0,
  "jul qty": 0,
  "jul rate": 0,
  "jul amount": 0,
  july: 0,
  "aug qty": 0,
  "aug rate": 0,
  "aug amount": 0,
  august: 0,
  "sep qty": 0,
      "sep rate": 0,
  "sep amount": 0,
  september: 0,
  "oct qty": 0,
  "oct rate": 0,
  "oct amount": 0,
  october: 0,
  "nov qty": 0,
  "nov rate": 0,
  "nov amount": 0,
  november: 0,
  "dec qty": 0,
  "dec rate": 0,
  "dec amount": 0,
  december: 0,
  "jan qty": 0,
  "jan rate": 0,
  "jan amount": 0,
  january: 0,
  "feb qty": 0,
  "feb rate": 0,
  "feb amount": 0,
  february: 0,
  "mar qty": 0,
  "mar rate": 0,
  "mar amount": 0,
  march : 0,
  budgetDetailsId: 0,
});

export const headerMonth = [
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
  "January",
  "February",
  "March",
];

export const monthToQuarter: Record<string, keyof import("../types/travel").totalschema> = {
  apr: "totalQ1",
  may: "totalQ1",
  jun: "totalQ1",
  jul: "totalQ2",
  aug: "totalQ2",
  sep: "totalQ2",
  oct: "totalQ3",
  nov: "totalQ3",
  dec: "totalQ3",
  jan: "totalQ4",
  feb: "totalQ4",
  mar: "totalQ4",
};

export const displayNameMap: Record<string, string> = {
  "Local conveyance (External)":    "Local",
  "Outstation travel (External)":   "Outstation",
  "Accomodation (External)":         "Hotel",
  "Per diem for employees (External)":        "Per deim",
};

export const displayColumnMap: Record<string, string> = {
  "apr qty": " No",
  "apr rate": " Rate",
  "apr amount": " Total",
  "april": "april",
  "may qty": " No",
  "may rate": " Rate",
  "may amount": " Total",
  "may": "may",
  "jun qty": " No",
  "jun rate": " Rate",
  "jun amount": " Total",
  "june": "june",
  "jul qty": " No",
  "jul rate": " Rate",
  "jul amount": " Total",
  "july": "july",
  "aug qty": " No",
  "aug rate": " Rate",
  "aug amount": " Total",
  "august": "august",
  "sep qty": " No",
  "sep rate": " Rate",
  "sep amount": " Total",
  "september": "september",
  "oct qty": " No",
  "oct rate": " Rate",
  "oct amount": " Total",
  "october": "october",
  "nov qty": "Nov No",
  "nov rate": "Nov Rate",
  "nov amount": "Nov Total",
  "november": "november",
  "dec qty": " No",
  "dec rate": " Rate",
  "dec amount": " Total",
  "december": "december",
    "jan qty": " No",
  "jan rate": " Rate",
  "jan amount": " Total",
  "january": "january",
  "feb qty": " No",
  "feb rate": " Rate",
  "feb amount": " Total",
  "february": "february",
  "mar qty": " No",
  "mar rate": " Rate",
  "mar amount": " Total",
  "march": "march",
};

export const monthMap: Record<string, string> = {
  jan: "january",
  feb: "february",
  mar: "march",
  apr: "april",
  may: "may",
  jun: "june",
  jul: "july",
  aug: "august",
  sep: "september",
  oct: "october",
  nov: "november",
  dec: "december",
};
